# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f8e53c07d335bafb131abbbb326f82d663a890712faeeea0a36b9f5e7f2037cf09831f2b7de5a9e783778978f37ad5f58af380781f87cce805f39887c57f04a

test:
  secret_key_base: 3e95746adb2d07b040b8aa5605ba86eeb02efd1bcc133d676e3bdd2937059bc1718f990240a19a64d9fd64cd667aa8e31ede36a01f2e0d06bd7a3aea21c766b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
